---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fioclient
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {STORAGECLASS}
---
apiVersion: v1
kind: Pod
metadata:
  name: fioclient
  # this label is important, it's how we determine the worker count
  labels:
    app: fioloadgen
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
  containers:
   - name: fioclient
     image: docker.io/pcuzner/fiotester
     env:
       - name: FIOMODE
         value: server
     volumeMounts:
       - name: testdata
         mountPath: /mnt
  volumes:
    - name: testdata
      persistentVolumeClaim:
        claimName: fioclient
        readOnly: false
