---
apiVersion: v1
kind: Pod
metadata:
  name: fiomgr
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
  containers:
   - name: fiomgr
     image: pcuzner/fiotester:1.5
     env:
     - name: FIOMODE
       value: client
