apiVersion: v1
kind: ServiceAccount
metadata:
  name: fioservice-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fioservice
rules:
  - apiGroups:
    - ""
    resources:
      - pods
      - storageclasses
    verbs:
      - get
      - list
  - apiGroups: 
    - extensions
    resources:
      - deployments
      - deployments/scale
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fioservice-binding
subjects:
  - kind: ServiceAccount
    name: fioservice-sa
roleRef:
  kind: Role
  name: fioservice
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fioservice
  labels:
    app: fioservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fioservice
  template:
    metadata:
      labels:
        app: fioservice
    spec:
      serviceAccountName: fioservice-sa
      containers:
      - name: fioservice
        image: pcuzner/fioservice:debug-v4
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: RUNTIME
          value: "container"
        # - name: TYPE
        #   value: 'local'
        - name: MODE
          value: "prod"
        - name: DEBUG
          value: "false"
        # command: [ 'usr/bin/tail']
        # args: ['-f','/dev/null']

