---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fioworker-!STORAGECLASS!
spec:
  selector:
    matchLabels:
      app: fioloadgen # has to match .spec.template.metadata.labels
  serviceName: "fioworker"
  replicas: !WORKERS! # by default is 1
  template:
    metadata:
      labels:
        app: fioloadgen # has to match .spec.selector.matchLabels
        storageclass: !STORAGECLASS!
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: fioclient
        image: pcuzner/fiotester
        env:
          - name: FIOMODE
            value: server
        volumeMounts:
          - name: testdata
            mountPath: /mnt
  volumeClaimTemplates:
  - metadata:
      name: testdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "!STORAGECLASS!"
      resources:
        requests:
          storage: 10Gi
