---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fioworker
spec:
  selector:
    matchLabels:
      app: fioloadgen # has to match .spec.template.metadata.labels
      storageclass: standard
  serviceName: "fioworker"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: fioloadgen # has to match .spec.selector.matchLabels
        storageclass: standard
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: fioclient
        image: pcuzner/fiotester:1.5
        env:
          - name: FIOMODE
            value: server
        volumeMounts:
          - name: testdata
            mountPath: /mnt
  volumeClaimTemplates:
  - metadata:
      name: testdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 10Gi
