---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fioworker-!STORAGECLASS!
spec:
  selector:
    matchLabels:
      app: fioloadgen # has to match .spec.template.metadata.labels
      storageclass: !STORAGECLASS!
  serviceName: "fioworker"
  replicas: !WORKERS! # by default is 1
  template:
    metadata:
      labels:
        app: fioloadgen # has to match .spec.selector.matchLabels
        storageclass: !STORAGECLASS!
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - fioloadgen
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
      - name: fioclient
        image: pcuzner/fiotester:1.5
        env:
          - name: FIOMODE
            value: server
        volumeMounts:
          - name: testdata
            mountPath: /mnt
  volumeClaimTemplates:
  - metadata:
      name: testdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "!STORAGECLASS!"
      resources:
        requests:
          storage: 10Gi
